#!/usr/bin/env bash
brew install git && brew cleanup
cd "$(dirname "${BASH_SOURCE}")"
WD=`pwd`
rm -f ~/.gitconfig
ln -s ${WD}/.gitconfig ~/.gitconfig && echo 'Link ~/.gitconfig'
rm -f ~/.gitignore
ln -s ${WD}/.gitignore ~/.gitignore && echo 'Link ~/.gitignore'
echo 'Configuring git.'
echo 'Type-in your full name: '
read NAME
echo 'Your email address: '
read EMAIL
echo 'GitHub user: '
read GITHUB_USER
if [[ ! -z "${NAME}" ]]; then
  echo "Add full name (${NAME}) to .gitconfig"
  git config --global user.name "${NAME}"
fi
if [[ ! -z "${EMAIL}" ]]; then
  echo "Add email (${EMAIL}) to .gitconfig"
  git config --global user.email "${EMAIL}"
fi
if [[ ! -z "${GITHUB_USER}" ]]; then
  echo "Add GitHub username (${GITHUB_USER}) to .gitconfig"
  git config --global github.user "${GITHUB_USER}"
fi
