#!/usr/bin/env bash
# history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head

alias a='vim ~/.aliases && source ~/.aliases'

alias tl='tmux list-sessions'
alias tka='tmux kill-session -a'

alias unlock='security unlock-keychain'

alias d='./deploy'
alias i='./install'
alias o='./open'
alias r='./run'
alias s='./styling'
alias t='./test'

alias -- -='cd -'
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias db='cd ~/Dropbox'
alias dl='cd ~/Downloads'
alias dn='cd ~/Dropbox/Notes'
alias rr='cd ~/Repositories'
alias dot='cd ~/Repositories/romanzolotarev/dotfiles'

alias gss='git-statuses'
alias gpp='git-pulls'
alias gpo='g po'
alias gp='g p'
alias gs='g s'
alias gca='g ca'
alias gl='g l'
alias gh='github .'
alias g='git'
alias c='clear'
alias gc='git-cal --ascii'

alias df='df -h | grep /dev/disk1'
alias du='du -h -d 1'

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag='--color'
else # OS X `ls`
  colorflag='-G'
fi

alias l="ls -aF ${colorflag}"
alias ll="ls -lhF ${colorflag}"
alias la="ls -laF ${colorflag}"
alias ls="command ls ${colorflag}"

alias sudo='sudo '
alias map='xargs -n1'
alias gurl='curl --compressed'
alias week='date +%V'

alias whois='whois -h whois-servers.net'
alias flushdns='dscacheutil -flushcache && killall -HUP mDNSResponder'

alias cleanopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder'
alias deleteds='sudo find ./ -name ".DS_Store" -depth -exec rm {} \;'
alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl'

alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'
alias path='echo -e ${PATH//:/\\n}'
alias spotlightoff='sudo mdutil -a -i off'
alias spotlighton='sudo mdutil -a -i on'

alias update='sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; sudo gem update --system; sudo gem update --no-document'
alias reload="exec $SHELL -l"
