#!/usr/bin/env bash
open https://itunes.apple.com/us/app/xcode/id497799835?mt=12
echo 'Install Xcode via App Store and press any key to continue'
read
xcode-select --install

repositories="${HOME}/Repositories"
user="${repositories}/romanzolotarev"
dotfiles="${user}/dotfiles"

mkdir -p ${repositories} 
mkdir -p ${user}
git clone https://github.com/romanzolotarev/dotfiles ${dotfiles} 
cd ${dotfiles}

./install-osx && ./install-ssh && ./install-dotfiles && ./install-vim
