#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE}")"

read -p \
  'Copying bash files. This may overwrite files in ~. Are you sure? (y/N) ' -n 1
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
  cd ./bash && \
  rsync --exclude '.DS_Store' -av --no-perms . $HOME && \
  source $HOME/.profile && \
  cd ..
fi