#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE}")"
git pull
git submodule init
git submodule update

cd vim
DIR="$HOME/.vim"
mkdir -p "$(DIR)"

cp -r autoload "$(DIR)/"
cp -r bundle "$(DIR)/"
cp .vimrc "$HOME/"
