#!/usr/bin/env bash
directory="${HOME}/.ssh"
host=$(scutil --get LocalHostName)
file="${directory}/${host}"
config="${directory}/config"

mkdir -p ${directory}
chmod 700 ${directory} 
ssh-keygen -t rsa -C ${host} -f ${file}
eval "$(ssh-agent -s)"
ssh-add ${file}
pbcopy < "${file}.pub"

cat <<EOF >> ${config}
Host github.com
  User git 
  Hostname github.com
  IdentityFile ${file}
EOF

cat <<EOM

The new public key copied into your clipboard.
Sign in at GitHub and paste your SSH key.
Then to test the connection run:

  $ ssh -T git@github.com -i ${file}

EOM
open https://github.com/settings/ssh
