#!/usr/bin/env bash
# cd "$(dirname "${BASH_SOURCE}")"
brew install mongo && brew cleanup
# if [ $? -eq 0 ]; then
#   rm -f /usr/local/etc/mongod.conf
#   ln -s "${PWD}/mongod.conf" /usr/local/etc/mongod.conf && echo 'Link mongod.conf'
# else
#   echo 'Can not install mongo. Check brew first.'
# fi

# To have launchd start mongodb at login:
#     ln -sfv /usr/local/opt/mongodb/*.plist ~/Library/LaunchAgents
# Then to load mongodb now:
#     launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
# Or, if you don't want/need launchctl, you can just run:
#     mongod --config /usr/local/etc/mongod.conf
