#!/usr/bin/env bash
echo -e "You're about to replace \e[33m~/.mutt\e[0m"
echo 'Sure?'
read
brew install mutt w3m isync notmuch ripmime msmtp 
rm -rf ${HOME}/.mutt
ln -s ${PWD}/mutt ${HOME}/.mutt && echo 'Link ~/.mutt'
touch ${HOME}/.mutt/aliases
ln -sf ${PWD}/msmtprc ${HOME}/.msmtprc && echo 'Link ~/.msmtprc'
ln -sf ${PWD}/mbsyncrc ${HOME}/.mbsyncrc && echo 'Link ~/.mbsyncrc'
ln -sf ${PWD}/notmuch-config ${HOME}/.notmuch-config && echo 'Link ~/.notmuch-config'
