#!/usr/bin/env bash

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Enable QuickTime Player autoplay
defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen 1

# Disables launching MacVim through a login shell
defaults write org.vim.MacVim MMLoginShell 0

# Add window paddings for MacVim
defaults write org.vim.MacVim MMTextInsetTop '20'
defaults write org.vim.MacVim MMTextInsetLeft '20'
defaults write org.vim.MacVim MMTextInsetBottom '20'
defaults write org.vim.MacVim MMTextInsetRight '20'
