#!/usr/bin/env bash
rm -rf ~/.npm
brew update && brew doctor && brew install node && brew cleanup && \
npm cache clear && \
npm install -g \
  coffee-script \
  coffeelint \
  js2coffee \
  html2jade \
  keybase
