#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Cask applications
#brew doctor
#brew install phinze/cask/brew-cask
#brew tap caskroom/versions
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Apps for every day
brew cask install divvy 
brew cask install alfred 
brew cask install arq 
brew cask install balsamiq-mockups 
brew cask install dropbox 
brew cask install flux 
brew cask install github
brew cask install google-chrome
brew cask install google-hangouts
brew cask install harvest
brew cask install imageoptim
brew cask install licecap
brew cask install multibit
brew cask install onepassword
brew cask install sublime-text3
brew cask install virtualbox
brew cask install appcleaner
brew cask install carbon-copy-cloner
brew cask install transmission 
brew cask install vlc
brew cask install skype

# the-unarchiver daisydisk fluid gpgtools imagealpha fluid kindle \
# send-to-kindle marked sketch skype subtitles teamviewer torbrowserbundle

# Cleanup
brew cask cleanup
brew cleanup

# Hide /opt from Finder
sudo chflags hidden /opt
