#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE}")"

if brew --version &> /dev/null; then
  echo 'Homebrew has been installed. Running brew doctor...'
  brew update && brew doctor && brew cleanup
else
  echo 'Installing Homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo 'Install formulas...'
brew install \
  bash \
  bash-completion \
  brew-cask \
  ctags \
  ffmpeg \
  gpg \
  git \
  hub \
  imagemagick \
  macvim --override-system-vim --with-lua \
  node \
  reattach-to-user-namespace \
  ruby \
  the_silver_searcher \
  tmux \
  wget
brew linkapps macvim
brew cleanup
