#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE}")"
echo 'Installing node.js and npm'

brew update && brew install node && brew cleanup
npm install -g \
  coffee-script \
  coffeelint \
  js2coffee \
  html2jade \
  keybase
