#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE}")"

if brew --version &> /dev/null; then
  echo 'Homebrew has been installed.'
else
  echo 'Installing Homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo 'Running brew doctor...'
# brew update && brew doctor

echo 'Install formulas...'
brew install \
  bash \
  bash-completion \
  ctags \
  ffmpeg \
  gpg \
  git \
  hub \
  imagemagick \
  node \
  reattach-to-user-namespace \
  ruby \
  the_silver_searcher \
  tmux \
  wget
brew install macvim --override-system-vim --with-lua
brew linkapps macvim

brew install caskroom/cask/brew-cask
brew cleanup
