#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install Cask applications
brew doctor
brew install phinze/cask/brew-cask
brew tap caskroom/versions
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Apps for every day
brew cask install alfred arq balsamiq-mockups dropbox flux github \
  google-chrome google-hangouts harvest imageoptim licecap multibit \
  onepassword sublime-text3 virtualbox appcleaner carbon-copy-cloner \
  transmission vlc

# the-unarchiver daisydisk fluid gpgtools imagealpha fluid kindle \
# send-to-kindle marked sketch skype subtitles teamviewer torbrowserbundle

# Cleanup
brew cask cleanup
brew cleanup

# Hide /opt from Finder
sudo chflags hidden /opt