#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE}")"
WD=$PWD
echo -e "You're about to replace \e[33m~/.vim\e[0m"
echo 'Sure?'
read
rm -rf ${HOME}/.vim && mkdir ${HOME}/.vim && echo 'Make ~/.vim'
mkdir ${HOME}/.vim/bundle && echo 'Make ~/.vim/bundle'
git clone https://github.com/gmarik/vundle.vim ${HOME}/.vim/bundle/vundle.vim
git clone https://github.com/shougo/vimproc.vim ${HOME}/.vim/bundle/vimproc.vim && cd ${HOME}/.vim/bundle/vimproc.vim && make
vim -u $WD/vimrc-install

# git clone https://github.com/shougo/neobundle.vim ${HOME}/.vim/bundle/neobundle.vim
# vim -N -u ${PWD}/vimrc-install -c "try | NeoBundleUpdate! $* | finally | qall! | endtry" -U NONE -i NONE -V1 -e -s
