	g submodule add https://github.com/chrishunt/xterm-color-table.vim.git
	g submodule add https://github.com/epmatsw/ag.vim.git
	g submodule add https://github.com/godlygeek/tabular.git
	g submodule add https://github.com/jelera/vim-javascript-syntax.git
	g submodule add https://github.com/kchmck/vim-coffee-script.git
	g submodule add https://github.com/kien/ctrlp.vim.git
	g submodule add https://github.com/mattn/gist-vim.git
	g submodule add https://github.com/mustache/vim-mustache-handlebars.git
	g submodule add https://github.com/othree/html5-syntax.vim.git
	g submodule add https://github.com/rizzatti/dash.vim.git
	g submodule add https://github.com/rizzatti/funcoo.vim.git
	g submodule add https://github.com/shougo/unite.vim.git
	g submodule add https://github.com/tpope/vim-abolish.git
	g submodule add https://github.com/tpope/vim-commentary.git
	g submodule add https://github.com/tpope/vim-fugitive.git
	g submodule add https://github.com/tpope/vim-liquid.git
	g submodule add https://github.com/tpope/vim-markdown.git
	g submodule add https://github.com/tpope/vim-repeat.git
	g submodule add https://github.com/tpope/vim-surround.git
	g submodule add https://github.com/tpope/vim-unimpaired.git
