#!/usr/bin/env bash
if brew --version &> /dev/null; then
  echo 'Running brew...'
  brew update && brew doctor && brew install vim --with-lua && brew cleanup
  if [ $? -eq 0 ]; then
    cd "$(dirname "${BASH_SOURCE}")"
    WD=`pwd`
    git pull
    git submodule init
    git submodule update
    git submodule foreach git pull origin master
    rm -f ~/.vimrc && ln -s ${WD}/.vimrc ~/.vimrc && echo 'Replace ~/.vimrc'
    rm -rf ~/.vim && mkdir -p ~/.vim && echo 'Replace ~/.vim'
    rm -rf ~/.vim/bundle && mkdir ~/.vim/bundle && echo 'Replace ~/.vim/bundle'
    git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
    git clone https://github.com/Shougo/vimproc ~/.vim/bundle/vimproc
    rm -f /usr/local/bin/colorscheme && ln -s ${WD}/colorscheme /usr/local/bin/colorscheme && echo 'Replace /usr/local/bin/colorscheme'
    cd ~/.vim/bundle/vimproc && make && cd -
    echo 'Done.'
  else
    echo 'Can not install vim. Check brew first.'
  fi
else
  echo 'Please install brew first.'
fi
