#!/usr/bin/env bash
brew install macvim --with-lua
if [ $? -eq 0 ]; then
  cd "$(dirname "${BASH_SOURCE}")"
  ln -sf "${PWD}/.gvimrc" ~/.gvimrc && echo 'Link ~/.gvimrc'
  echo 'Done.'
  defaults write org.vim.MacVim MMTextInsetTop '30'
  defaults write org.vim.MacVim MMTextInsetLeft '30'
  defaults write org.vim.MacVim MMTextInsetBottom '30'
  defaults write org.vim.MacVim MMTextInsetRight '30'
else
  echo 'Can not install macvim. Check brew first.'
fi
