#!/usr/bin/env bash

# Install Cask applications
echo 'Running brew doctor...'
if brew doctor; then
  echo 'Installing brew-cask...'
  brew tap caskroom/cask
  brew install brew-cask
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"
  echo 'Hide /opt'
  chflags hidden /opt
  echo 'Installing apps...'
  brew cask install alfred
  brew cask install appcleaner
  brew cask install arq
  brew cask install balsamiq-mockups
  brew cask install carbon-copy-cloner
  brew cask install divvy
  brew cask install dropbox
  brew cask install flux
  brew cask install github
  brew cask install google-chrome
  brew cask install google-hangouts
  brew cask install harvest
  brew cask install imageoptim
  brew cask install licecap
  brew cask install multibit
  brew cask install onepassword
  brew cask install virtualbox
  brew cask install vlc
  # paparazzi vagrant slack the-unarchiver daisydisk fluid gpgtools imagealpha
  # transmission fluid kindle send-to-kindle marked sketch skype subtitles
  # teamviewer torbrowserbundle skype
  brew linkapps
  brew cask cleanup
else
  echo 'Can not install brew-cask. Please fix brew first.'
fi
