#!/bin/bash
# Insipred by view_attachment.sh by Eric Gebhart
# http://linsec.ca/Using_mutt_on_OS_X#mailcap
tmpdir="$HOME/.mutt/tmp/mutt_attach"
debug_file=$tmpdir/debug
debug="yes"
mkdir -p $tmpdir
# rm -f $tmpdir/*
filename=`basename $1`
file=`echo $filename | cut -d"." -f1`

if [ $debug = "yes" ]; then
  echo "1:" $1 > $debug_file
  echo "Filename:"$filename >> $debug_file
  echo "File:"$file >> $debug_file
  echo "===========================" >> $debug_file
fi

newfile=$tmpdir/$filename
cp $1 $newfile

if [ $debug = "yes" ]; then
  echo "File:" $file "TYPE:" $type >> $debug_file
  echo "Newfile:" $newfile >> $debug_file
fi

open -a Preview $newfile
