#!/usr/bin/env bash
cd "$(dirname "${BASH_SOURCE}")"
WD=`pwd`
ln -sf ${WD}/.aliases ~/.aliases && echo 'Link ~/.aliases' && source ~/.aliases
ln -sf ${WD}/.completions ~/.completions && echo 'Link ~/.completions' && source ~/.completions
ln -sf ${WD}/.path ~/.path && echo 'Link ~/.path' && source ~/.path
ln -sf ${WD}/.prompt ~/.prompt && echo 'Link ~/.prompt' && source ~/.prompt
ln -sf ${WD}/.bash_profile ~/.bash_profile && echo 'Link ~/.bash_profile' && source ~/.bash_profile
ln -sf ${WD}/.inputrc ~/.inputrc && echo 'Link ~/.inputrc'
if brew --version &> /dev/null; then
  echo 'Homebrew has been installed. Running brew doctor...'
  brew update && brew doctor && brew cleanup
else
  echo 'Installing Homebrew...'
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  echo 'Installing bash...'
  brew install bash bash-completion
  # bash bash-completion brew-cask ctags ffmpeg git git-cal hub imagemagick
  # mongodb node openssl phantomjs python reattach-to-user-namespace ruby
  # sqlite the_silver_searcher tmux vim wget
fi
