#!/usr/bin/env bash

if [[ ! -z ${1} ]]; then
  sudo scutil --set ComputerName "${1}"
  sudo scutil --set HostName "${1}"
  sudo scutil --set LocalHostName "${1}"
  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "${1}"
else
  echo -e "usage: ${0##*/} name"
fi

