#!/usr/bin/env bash
if brew --version &> /dev/null; then
  echo 'Running brew...'
  brew update && brew doctor && brew install tmux && brew install reattach-to-user-namespace && brew cleanup
  if [ $? -eq 0 ]; then
    cd "$(dirname "${BASH_SOURCE}")"
    WD=`pwd`
    rm -f ~/.tmux.conf && ln -s ${WD}/.tmux.conf ~/.tmux.conf && echo 'Replace ~/.tmux.conf'
    rm -f /usr/local/bin/tmux-battery && ln -s ${WD}/tmux-battery /usr/local/bin/tmux-battery && echo 'Replace /usr/local/bin/tmux-battery'
    rm -f /usr/local/bin/tmux-session && ln -s ${WD}/tmux-session /usr/local/bin/tmux-session && echo 'Replace /usr/local/bin/tmux-session'
  else
    echo 'Can not install tmux. Check brew first.'
  fi
else
  echo 'Please install brew first.'
fi
