#!/usr/bin/env bash
brew install tmux && brew install reattach-to-user-namespace 
if [ $? -eq 0 ]; then
  gem install tmuxinator
  cd "$(dirname "${BASH_SOURCE}")"
  WD=`pwd`
  ln -sf ${WD}/.tmux.conf ~/.tmux.conf && echo 'Link ~/.tmux.conf'
  ln -sf ${WD}/tmux-battery /usr/local/bin/tmux-battery && echo 'Link /usr/local/bin/tmux-battery'
  ln -sf ${WD}/tmux-session /usr/local/bin/tmux-session && echo 'Link /usr/local/bin/tmux-session'
else
  echo 'Can not install tmux. Check brew first.'
fi
