#!/bin/sh
DATE=`date +%Y%m`
ORIGINAL="originals/${DATE}"
PRESSED="900k/${DATE}"

mkdir -p ${ORIGINAL}
mkdir -p ${PRESSED}

time ffmpeg -loglevel warning -stats -i ${1} -b:v 900k "${PRESSED}/${1}"
mv ${1} ${ORIGINAL}
